spring:
  application:
    name: homemate
  profiles:
    include:
      - email
      - db
      - cons
  servlet:
    multipart:
      max-file-size: 100MB
server:
  port: 8080
logging:
  level:
    web: trace
