apiVersion: v1
kind: Service
metadata:
  name: your-app-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Uygulamanızın dinlediği port
  selector:
    app: your-app
